### PR TITLE
Update for deprecations in xarray.py

### PR DESCRIPTION
**Pull request by raybellwaves**
Replaced xr.Coordinate with xr.IndexVariable.

Also made the edit of the ticket by @lynch123.

### CODE REVIEW

**Comment by ajdawson** [comment]
Please fix the minor formatting issues as reported in the test output, otherwise seems fine.

**Comment by raybellwaves** [comment]
I'll do this tomorrow. My first pull request so thanks for making it fairly easy.
I'll update xr.Coordinate in test/reference.py in the next pull request as well.

**Comment by ajdawson** [comment]
You may as well include the changes in all files that use `Coordinate` in this PR too.

**Comment by ajdawson** [comment]
Cheers @raybellwaves

**Comment by raybellwaves** [comment]
Cheers. Awesome package

**Pull request merged**
